version: '2.4'
services:
  gluetun:
    container_name: glutun-vpn
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    volumes:
      - /portainer/Files/AppData/Config/qBittorrent:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=surfshark
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=oD8r97FzARwFG8vn42LVNHoTqU22P+1ew536ujprS3A=
      - WIREGUARD_ADDRESSES=10.14.0.2/16
      - SERVER_COUNTRIES=United States,Netherlands,Switzerland,Australia,United Kingdom,Canada
    ports:
      - "8722:5000/tcp"
      - "2880:1080/tcp"
      - "6881:6881/tcp"
      - "8080:8080/tcp"
      - "9117:9117/tcp"
      - "6881:6881/udp"
    restart: "unless-stopped"
  
  proxy-server:
    container_name: "tamilmv-torznab-proxy"
    image: "febinbaiju/tamilmv-torznab-proxy"
    environment:
      - TAMILMV_URL=https://www.1tamilmv.wtf/
    depends_on:
      gluetun:
        condition: service_healthy
    network_mode: "service:gluetun"
    restart: "unless-stopped"

  socks5-proxy:
    container_name: "go-socks5-proxy"
    image: "serjs/go-socks5-proxy"
    depends_on:
      gluetun:
        condition: service_healthy
    network_mode: "service:gluetun"
    restart: "unless-stopped"