version: '3'
services:
  gluetun:
    container_name: glutun-vpn
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    volumes:
      - /portainer/Files/AppData/Config/glutun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - OPENVPN_USER=I3cZPlSUx6cMRKiU
      - OPENVPN_PASSWORD=GGksyoZYxebMvyn4TV3yYp4u1bjJO7W2
      - FREE_ONLY=on
      - SERVER_COUNTRIES=Netherlands
    ports:
      - "8722:5000/tcp"
      - "2880:1080/tcp"
      - "9117:9117/tcp"
    restart: "unless-stopped"
  
  proxy-server:
    container_name: "tamilmv-torznab-proxy"
    image: "febinbaiju/tamilmv-torznab-proxy"
    volumes:
      - /portainer/Files/AppData/Config/tamilmv-stack:/database
    environment:
      - TAMILMV_URL=https://www.1tamilmv.tips
    depends_on:
      gluetun:
        condition: service_healthy
    network_mode: "service:gluetun"
    restart: "unless-stopped"

  socks5-proxy:
    container_name: "go-socks5-proxy"
    image: "serjs/go-socks5-proxy"
    depends_on:
      gluetun:
        condition: service_healthy
    network_mode: "service:gluetun"
    restart: "unless-stopped"
  
  jackett-proxy:
    container_name: "jackett"
    image: "linuxserver/jackett:latest"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /portainer/Files/AppData/Config/Jackett:/config
      - /portainer/Downloads:/downloads
    depends_on:
      gluetun:
        condition: service_healthy
    network_mode: "service:gluetun"
    restart: "unless-stopped"
